#!/bin/sh
#this is to keep stale tails from hanging around...
pkill -P 1 -f "tail -f /home/segfault/files/sh_in"
mkdir -p /home/segfault/files
mkfifo /home/segfault/files/sh_in
mkfifo /home/segfault/files/sh_out
exec setuidgid segfault tail -f /home/segfault/files/sh_in | su -l segfault 2>&1 > /home/segfault/files/sh_out 2>&1
